# version format
version: 0.1.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=-beta (hyphen must be included)
install:
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=7.1.8
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds
build: off

artifacts:
  - path: BuildPackage\Package\*.nupkg
  - path: BuildPackage\Package\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-crop-healer/
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: master